/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DefChar91DotChar93htmlRouteImport } from './routes/root/def[.]html'
import { Route as AboutRouteImport } from './routes/root/about'
import { Route as TestAbcChar91DotChar93htmlRouteImport } from './routes/abc[.]html'

const DefChar91DotChar93htmlRoute = DefChar91DotChar93htmlRouteImport.update({
  id: '/def.html',
  path: '/def.html',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TestAbcChar91DotChar93htmlRoute =
  TestAbcChar91DotChar93htmlRouteImport.update({
    id: '/abc.html',
    path: '/abc.html',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/abc.html': typeof TestAbcChar91DotChar93htmlRoute
  '/about': typeof AboutRoute
  '/def.html': typeof DefChar91DotChar93htmlRoute
}
export interface FileRoutesByTo {
  '/abc.html': typeof TestAbcChar91DotChar93htmlRoute
  '/about': typeof AboutRoute
  '/def.html': typeof DefChar91DotChar93htmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/abc.html': typeof TestAbcChar91DotChar93htmlRoute
  '/about': typeof AboutRoute
  '/def.html': typeof DefChar91DotChar93htmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/abc.html' | '/about' | '/def.html'
  fileRoutesByTo: FileRoutesByTo
  to: '/abc.html' | '/about' | '/def.html'
  id: '__root__' | '/abc.html' | '/about' | '/def.html'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TestAbcChar91DotChar93htmlRoute: typeof TestAbcChar91DotChar93htmlRoute
  AboutRoute: typeof AboutRoute
  DefChar91DotChar93htmlRoute: typeof DefChar91DotChar93htmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/def.html': {
      id: '/def.html'
      path: '/def.html'
      fullPath: '/def.html'
      preLoaderRoute: typeof DefChar91DotChar93htmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abc.html': {
      id: '/abc.html'
      path: '/abc.html'
      fullPath: '/abc.html'
      preLoaderRoute: typeof TestAbcChar91DotChar93htmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  TestAbcChar91DotChar93htmlRoute: TestAbcChar91DotChar93htmlRoute,
  AboutRoute: AboutRoute,
  DefChar91DotChar93htmlRoute: DefChar91DotChar93htmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
